--1.映射HBase表(Car_Data_BCA)
CREATE EXTERNAL TABLE Car_Data_BCA(ROWKEY BINARY,S2 STRING,S3a STRING,S7 STRING,S8a STRING,S8b STRING,YR STRING,MTH STRING, CX ARRAY<STRING>,IQS ARRAY<STRING>,CD ARRAY<STRING>,GJ ARRAY<STRING>,JK ARRAY<STRING>,FM STRING,RY ARRAY<STRING>,R_B1a ARRAY<STRING>,R_B2a ARRAY<STRING>,R_B3a ARRAY<STRING>,B3b ARRAY<STRING>,G1 STRING,S9 STRING,S10 STRING,Q2a STRING,Q2b STRING,Q2c STRING,B1 ARRAY<STRING>,B2 ARRAY<STRING>,B3 ARRAY<STRING>,B4 ARRAY<STRING>,B5 ARRAY<STRING>,B6 ARRAY<STRING>,B7 ARRAY<STRING>,B8 ARRAY<STRING>,A_B1a ARRAY<STRING>,A_B2a ARRAY<STRING>,A_B3a ARRAY<STRING>,B4a ARRAY<STRING>,C1 ARRAY<STRING>,C2 ARRAY<STRING>,C3 ARRAY<STRING>,C4 ARRAY<STRING>,C5 ARRAY<STRING>,A1 ARRAY<STRING>,A2 ARRAY<STRING>,A3 ARRAY<STRING>,G ARRAY<STRING>,RDINT1 ARRAY<STRING>,BRDINT2 ARRAY<STRING>,BRDINT3 ARRAY<STRING>,IQSINT3 ARRAY<STRING>,IQSINT2 ARRAY<STRING>,IQSINT1 ARRAY<STRING>,S11 STRING,S12 STRING,S13 STRING,sid BINARY,ATT ARRAY<STRING>,IMG ARRAY<STRING>,A4 ARRAY<STRING>,C6 ARRAY<STRING>,S3b STRING,attimg1 ARRAY<STRING>,attimg2 ARRAY<STRING>,attimg3 ARRAY<STRING>)
ROW FORMAT DELIMITED
COLLECTION ITEMS TERMINATED BY ','
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping"=":key,R:S2,R:S3a,R:S7,R:S8a,R:S8b,R:YR,R:MTH,R:CX,R:IQS,R:CD,R:GJ,R:JK,R:FM,R:RY,R:B1a,R:B2a,R:B3a,R:B3b,R:G1,A:S9,A:S10,A:Q2a,A:Q2b,A:Q2c,A:B1,A:B2,A:B3,A:B4,A:B5,A:B6,A:B7,A:B8,A:B1a,A:B2a,A:B3a,A:B4a,A:C1,A:C2,A:C3,A:C4,A:C5,A:A1,A:A2,A:A3,A:G,R:BRDINT1,R:BRDINT2,R:BRDINT3,R:IQSINT3,R:IQSINT2,R:IQSINT1,A:S11,A:S12,A:S13,A:Sid,R:ATT,R:IMG,A:A4,A:C6,A:S3b,R:ATTIMG1,R:ATTIMG2,R:ATTIMG3")
TBLPROPERTIES("hbase.table.name" = "Car_Data_BCA");


--1.映射HBase表(Car_Data_BCA2)
CREATE EXTERNAL TABLE Car_Data_BCA2(ROWKEY BINARY,PID BINARY,S2 STRING,S3a STRING,S7 STRING,S8a STRING,S8b STRING,YR STRING,MTH STRING, CX ARRAY<STRING>,IQS ARRAY<STRING>,CD ARRAY<STRING>,GJ ARRAY<STRING>,JK ARRAY<STRING>,FM STRING,RY ARRAY<STRING>,R_B1a ARRAY<STRING>,R_B2a ARRAY<STRING>,R_B3a ARRAY<STRING>,B3b ARRAY<STRING>,G1 STRING,S9 STRING,S10 STRING,Q2a STRING,Q2b STRING,Q2c STRING,B1 ARRAY<STRING>,B2 ARRAY<STRING>,B3 ARRAY<STRING>,B4 ARRAY<STRING>,B5 ARRAY<STRING>,B6 ARRAY<STRING>,B7 ARRAY<STRING>,B8 ARRAY<STRING>,A_B1a ARRAY<STRING>,A_B2a ARRAY<STRING>,A_B3a ARRAY<STRING>,B4a ARRAY<STRING>,C1 ARRAY<STRING>,C2 ARRAY<STRING>,C3 ARRAY<STRING>,C4 ARRAY<STRING>,C5 ARRAY<STRING>,A1 ARRAY<STRING>,A2 ARRAY<STRING>,A3 ARRAY<STRING>,G ARRAY<STRING>,RDINT1 ARRAY<STRING>,BRDINT2 ARRAY<STRING>,BRDINT3 ARRAY<STRING>,IQSINT3 ARRAY<STRING>,IQSINT2 ARRAY<STRING>,IQSINT1 ARRAY<STRING>,S11 STRING,S12 STRING,S13 STRING,sid BINARY,ATT ARRAY<STRING>,IMG ARRAY<STRING>,A4 ARRAY<STRING>,C6 STRING,S3b STRING,attimg1 ARRAY<STRING>,attimg2 ARRAY<STRING>,attimg3 ARRAY<STRING>)
ROW FORMAT DELIMITED
COLLECTION ITEMS TERMINATED BY ','
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping"=":key,A:PID,R:S2,R:S3a,R:S7,R:S8a,R:S8b,R:YR,R:MTH,R:CX,R:IQS,R:CD,R:GJ,R:JK,R:FM,R:RY,R:B1a,R:B2a,R:B3a,R:B3b,R:G1,A:S9,A:S10,A:Q2a,A:Q2b,A:Q2c,A:B1,A:B2,A:B3,A:B4,A:B5,A:B6,A:B7,A:B8,A:B1a,A:B2a,A:B3a,A:B4a,A:C1,A:C2,A:C3,A:C4,A:C5,A:A1,A:A2,A:A3,A:G,R:BRDINT1,R:BRDINT2,R:BRDINT3,R:IQSINT3,R:IQSINT2,R:IQSINT1,A:S11,A:S12,A:S13,A:Sid,R:ATT,R:IMG,A:A4,A:C6,A:S3b,R:ATTIMG1,R:ATTIMG2,R:ATTIMG3")
TBLPROPERTIES("hbase.table.name" = "Car_Data_BCA2");

--2.映射HBase表(Car_Data_IQS)
CREATE EXTERNAL TABLE Car_Data_IQS(ROWKEY BINARY,S2 STRING,S3a STRING,S7 STRING,S8a STRING,S8b STRING,YR STRING,MTH STRING, BCX ARRAY<STRING>,IQS ARRAY<STRING>,CD ARRAY<STRING>,BGJ ARRAY<STRING>,BJK ARRAY<STRING>,FM STRING,BRY ARRAY<STRING>,R_B1a ARRAY<STRING>,R_B2a ARRAY<STRING>,R_B3a ARRAY<STRING>,B3b ARRAY<STRING>,G1 STRING,S9 STRING,S10 STRING,Q2a STRING,Q2b STRING,Q2c STRING,B1 ARRAY<STRING>,B2 ARRAY<STRING>,B3 ARRAY<STRING>,B4 ARRAY<STRING>,B5 ARRAY<STRING>,B6 ARRAY<STRING>,B7 ARRAY<STRING>,B8 ARRAY<STRING>,A_B1a ARRAY<STRING>,A_B2a ARRAY<STRING>,A_B3a ARRAY<STRING>,B4a ARRAY<STRING>,C1 ARRAY<STRING>,C2 ARRAY<STRING>,C3 ARRAY<STRING>,C4 ARRAY<STRING>,C5 ARRAY<STRING>,A1 ARRAY<STRING>,A2 ARRAY<STRING>,A3 ARRAY<STRING>,G ARRAY<STRING>,BRDINT1 ARRAY<STRING>,BRDINT2 ARRAY<STRING>,BRDINT3 ARRAY<STRING>,IQSINT3 ARRAY<STRING>,IQSINT2 ARRAY<STRING>,IQSINT1 ARRAY<STRING>)
ROW FORMAT DELIMITED
COLLECTION ITEMS TERMINATED BY ','
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping"=":key,R:S2,R:S3a,R:S7,R:S8a,R:S8b,R:YR,R:MTH,R:BCX,R:IQS,R:CD,R:BGJ,R:BJK,R:FM,R:BRY,R:B1a,R:B2a,R:B3a,R:B3b,R:G1,A:S9,A:S10,A:Q2a,A:Q2b,A:Q2c,A:B1,A:B2,A:B3,A:B4,A:B5,A:B6,A:B7,A:B8,A:B1a,A:B2a,A:B3a,A:B4a,A:C1,A:C2,A:C3,A:C4,A:C5,A:A1,A:A2,A:A3,A:G,R:BRDINT1,R:BRDINT2,R:BRDINT3,R:IQSINT3,R:IQSINT2,R:IQSINT1")
TBLPROPERTIES("hbase.table.name" = "Car_Data_IQS");

--3.映射HBase表(Car_Data_IQS_HalfY)
CREATE EXTERNAL TABLE Car_Data_IQS_HalfY(ROWKEY BINARY,S2 STRING,S3a STRING,S7 STRING,S8a STRING,S8b STRING,YR STRING,MTH STRING, BCX ARRAY<STRING>,IQS ARRAY<STRING>,CD ARRAY<STRING>,BGJ ARRAY<STRING>,BJK ARRAY<STRING>,FM STRING,BRY ARRAY<STRING>,R_B1a ARRAY<STRING>,R_B2a ARRAY<STRING>,R_B3a ARRAY<STRING>,B3b ARRAY<STRING>,G1 STRING,S9 STRING,S10 STRING,Q2a STRING,Q2b STRING,Q2c STRING,B1 ARRAY<STRING>,B2 ARRAY<STRING>,B3 ARRAY<STRING>,B4 ARRAY<STRING>,B5 ARRAY<STRING>,B6 ARRAY<STRING>,B7 ARRAY<STRING>,B8 ARRAY<STRING>,A_B1a ARRAY<STRING>,A_B2a ARRAY<STRING>,A_B3a ARRAY<STRING>,B4a ARRAY<STRING>,C1 ARRAY<STRING>,C2 ARRAY<STRING>,C3 ARRAY<STRING>,C4 ARRAY<STRING>,C5 ARRAY<STRING>,A1 ARRAY<STRING>,A2 ARRAY<STRING>,A3 ARRAY<STRING>,G ARRAY<STRING>,BRDINT1 ARRAY<STRING>,BRDINT2 ARRAY<STRING>,BRDINT3 ARRAY<STRING>,IQSINT3 ARRAY<STRING>,IQSINT2 ARRAY<STRING>,IQSINT1 ARRAY<STRING>)
ROW FORMAT DELIMITED
COLLECTION ITEMS TERMINATED BY ','
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping"=":key,R:S2,R:S3a,R:S7,R:S8a,R:S8b,R:YR,R:MTH,R:BCX,R:IQS,R:CD,R:BGJ,R:BJK,R:FM,R:BRY,R:B1a,R:B2a,R:B3a,R:B3b,R:G1,A:S9,A:S10,A:Q2a,A:Q2b,A:Q2c,A:B1,A:B2,A:B3,A:B4,A:B5,A:B6,A:B7,A:B8,A:B1a,A:B2a,A:B3a,A:B4a,A:C1,A:C2,A:C3,A:C4,A:C5,A:A1,A:A2,A:A3,A:G,R:BRDINT1,R:BRDINT2,R:BRDINT3,R:IQSINT3,R:IQSINT2,R:IQSINT1")
TBLPROPERTIES("hbase.table.name" = "Car_Data_IQS_HalfY");

--4.映射HBase表(Car_Data_IQS_Quarter)
CREATE EXTERNAL TABLE Car_Data_IQS_Quarter(ROWKEY BINARY,S2 STRING,S3a STRING,S7 STRING,S8a STRING,S8b STRING,YR STRING,MTH STRING, BCX ARRAY<STRING>,IQS ARRAY<STRING>,CD ARRAY<STRING>,BGJ ARRAY<STRING>,BJK ARRAY<STRING>,FM STRING,BRY ARRAY<STRING>,R_B1a ARRAY<STRING>,R_B2a ARRAY<STRING>,R_B3a ARRAY<STRING>,B3b ARRAY<STRING>,G1 STRING,S9 STRING,S10 STRING,Q2a STRING,Q2b STRING,Q2c STRING,B1 ARRAY<STRING>,B2 ARRAY<STRING>,B3 ARRAY<STRING>,B4 ARRAY<STRING>,B5 ARRAY<STRING>,B6 ARRAY<STRING>,B7 ARRAY<STRING>,B8 ARRAY<STRING>,A_B1a ARRAY<STRING>,A_B2a ARRAY<STRING>,A_B3a ARRAY<STRING>,B4a ARRAY<STRING>,C1 ARRAY<STRING>,C2 ARRAY<STRING>,C3 ARRAY<STRING>,C4 ARRAY<STRING>,C5 ARRAY<STRING>,A1 ARRAY<STRING>,A2 ARRAY<STRING>,A3 ARRAY<STRING>,G ARRAY<STRING>,BRDINT1 ARRAY<STRING>,BRDINT2 ARRAY<STRING>,BRDINT3 ARRAY<STRING>,IQSINT3 ARRAY<STRING>,IQSINT2 ARRAY<STRING>,IQSINT1 ARRAY<STRING>)
ROW FORMAT DELIMITED
COLLECTION ITEMS TERMINATED BY ','
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping"=":key,R:S2,R:S3a,R:S7,R:S8a,R:S8b,R:YR,R:MTH,R:BCX,R:IQS,R:CD,R:BGJ,R:BJK,R:FM,R:BRY,R:B1a,R:B2a,R:B3a,R:B3b,R:G1,A:S9,A:S10,A:Q2a,A:Q2b,A:Q2c,A:B1,A:B2,A:B3,A:B4,A:B5,A:B6,A:B7,A:B8,A:B1a,A:B2a,A:B3a,A:B4a,A:C1,A:C2,A:C3,A:C4,A:C5,A:A1,A:A2,A:A3,A:G,R:BRDINT1,R:BRDINT2,R:BRDINT3,R:IQSINT3,R:IQSINT2,R:IQSINT1")
TBLPROPERTIES("hbase.table.name" = "Car_Data_IQS_Quarter");

--5.映射HBase表(Car_Data_IQS_Raw)
CREATE EXTERNAL TABLE Car_Data_IQS_Raw(ROWKEY BINARY,S2 STRING,S3a STRING,S7 STRING,S8a STRING,S8b STRING,YR STRING,MTH STRING, BCX ARRAY<STRING>,IQS ARRAY<STRING>,CD ARRAY<STRING>,BGJ ARRAY<STRING>,BJK ARRAY<STRING>,FM STRING,BRY ARRAY<STRING>,R_B1a ARRAY<STRING>,R_B2a ARRAY<STRING>,R_B3a ARRAY<STRING>,B3b ARRAY<STRING>,G1 STRING,S9 STRING,S10 STRING,Q2a STRING,Q2b STRING,Q2c STRING,B1 ARRAY<STRING>,B2 ARRAY<STRING>,B3 ARRAY<STRING>,B4 ARRAY<STRING>,B5 ARRAY<STRING>,B6 ARRAY<STRING>,B7 ARRAY<STRING>,B8 ARRAY<STRING>,A_B1a ARRAY<STRING>,A_B2a ARRAY<STRING>,A_B3a ARRAY<STRING>,B4a ARRAY<STRING>,C1 ARRAY<STRING>,C2 ARRAY<STRING>,C3 ARRAY<STRING>,C4 ARRAY<STRING>,C5 ARRAY<STRING>,A1 ARRAY<STRING>,A2 ARRAY<STRING>,A3 ARRAY<STRING>,G ARRAY<STRING>,BRDINT1 ARRAY<STRING>,BRDINT2 ARRAY<STRING>,BRDINT3 ARRAY<STRING>,IQSINT3 ARRAY<STRING>,IQSINT2 ARRAY<STRING>,IQSINT1 ARRAY<STRING>)
ROW FORMAT DELIMITED
COLLECTION ITEMS TERMINATED BY ','
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping"=":key,R:S2,R:S3a,R:S7,R:S8a,R:S8b,R:YR,R:MTH,R:BCX,R:IQS,R:CD,R:BGJ,R:BJK,R:FM,R:BRY,R:B1a,R:B2a,R:B3a,R:B3b,R:G1,A:S9,A:S10,A:Q2a,A:Q2b,A:Q2c,A:B1,A:B2,A:B3,A:B4,A:B5,A:B6,A:B7,A:B8,A:B1a,A:B2a,A:B3a,A:B4a,A:C1,A:C2,A:C3,A:C4,A:C5,A:A1,A:A2,A:A3,A:G,R:BRDINT1,R:BRDINT2,R:BRDINT3,R:IQSINT3,R:IQSINT2,R:IQSINT1")
TBLPROPERTIES("hbase.table.name" = "Car_Data_IQS_Raw");

--6.映射HBase表(Car_Data_IQS_Year)
CREATE EXTERNAL TABLE Car_Data_IQS_Year(ROWKEY BINARY,S2 STRING,S3a STRING,S7 STRING,S8a STRING,S8b STRING,YR STRING,MTH STRING, BCX ARRAY<STRING>,IQS ARRAY<STRING>,CD ARRAY<STRING>,BGJ ARRAY<STRING>,BJK ARRAY<STRING>,FM STRING,BRY ARRAY<STRING>,R_B1a ARRAY<STRING>,R_B2a ARRAY<STRING>,R_B3a ARRAY<STRING>,B3b ARRAY<STRING>,G1 STRING,S9 STRING,S10 STRING,Q2a STRING,Q2b STRING,Q2c STRING,B1 ARRAY<STRING>,B2 ARRAY<STRING>,B3 ARRAY<STRING>,B4 ARRAY<STRING>,B5 ARRAY<STRING>,B6 ARRAY<STRING>,B7 ARRAY<STRING>,B8 ARRAY<STRING>,A_B1a ARRAY<STRING>,A_B2a ARRAY<STRING>,A_B3a ARRAY<STRING>,B4a ARRAY<STRING>,C1 ARRAY<STRING>,C2 ARRAY<STRING>,C3 ARRAY<STRING>,C4 ARRAY<STRING>,C5 ARRAY<STRING>,A1 ARRAY<STRING>,A2 ARRAY<STRING>,A3 ARRAY<STRING>,G ARRAY<STRING>,BRDINT1 ARRAY<STRING>,BRDINT2 ARRAY<STRING>,BRDINT3 ARRAY<STRING>,IQSINT3 ARRAY<STRING>,IQSINT2 ARRAY<STRING>,IQSINT1 ARRAY<STRING>)
ROW FORMAT DELIMITED
COLLECTION ITEMS TERMINATED BY ','
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping"=":key,R:S2,R:S3a,R:S7,R:S8a,R:S8b,R:YR,R:MTH,R:BCX,R:IQS,R:CD,R:BGJ,R:BJK,R:FM,R:BRY,R:B1a,R:B2a,R:B3a,R:B3b,R:G1,A:S9,A:S10,A:Q2a,A:Q2b,A:Q2c,A:B1,A:B2,A:B3,A:B4,A:B5,A:B6,A:B7,A:B8,A:B1a,A:B2a,A:B3a,A:B4a,A:C1,A:C2,A:C3,A:C4,A:C5,A:A1,A:A2,A:A3,A:G,R:BRDINT1,R:BRDINT2,R:BRDINT3,R:IQSINT3,R:IQSINT2,R:IQSINT1")
TBLPROPERTIES("hbase.table.name" = "Car_Data_IQS_Year");

--7.映射HBase表(Car_Data_RawG)
CREATE EXTERNAL TABLE Car_Data_RawG(ROWKEY BINARY,D STRING,YR STRING,MTH STRING,CX ARRAY<STRING>,GJ ARRAY<STRING>,JK ARRAY<STRING>,RY ARRAY<STRING>,S7 STRING,S2 STRING,S8a STRING,S8b STRING,G1 STRING,G2 STRING,G3 STRING,G4 STRING,G5 STRING,G8 STRING,G9 STRING,G10 STRING,G11 STRING,G12 STRING,G13 STRING,G14 STRING,G15 STRING,G16 STRING,G17 STRING,G18 STRING,G19 STRING,G20 STRING,G21 STRING,G22 STRING,G23 STRING,G24 STRING)
ROW FORMAT DELIMITED
COLLECTION ITEMS TERMINATED BY  ','
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping"=":key,R:D,R:YR,R:MTH,R:CX,R:GJ,R:JK,R:RY,R:S7,R:S2,R:S8a,R:S8b,A:G1,A:G2,A:G3,A:G4,A:G5,A:G8,A:G9,A:G10,A:G11,A:G12,A:G13,A:G14,A:G15,A:G16,A:G17,A:G18,A:G19,A:G20,A:G21,A:G22,A:G23,A:G24")
TBLPROPERTIES("hbase.table.name" = "Car_Data_RawG");

--8.映射HBase表(Car_Data_RawS)
CREATE EXTERNAL TABLE Car_Data_RawS(ROWKEY BINARY,D STRING,YR STRING,MTH STRING,CX ARRAY<STRING>,GJ ARRAY<STRING>,JK ARRAY<STRING>,RY ARRAY<STRING>,B2a STRING,B3b STRING,A_S2 STRING,S3a STRING,A_S8a STRING,A_S8b STRING,A_S7 STRING,S3b STRING,S4 STRING,S5 STRING,S6 STRING,S9 STRING,S10 STRING,S11 STRING,S12 STRING,S13 STRING,R_S7 STRING,R_S2 STRING,R_S8a STRING,R_S8b STRING,Q1 STRING,S1 STRING)
ROW FORMAT DELIMITED
COLLECTION ITEMS TERMINATED BY  ','
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping"=":key,R:D,R:YR,R:MTH,R:CX,R:GJ,R:JK,R:RY,R:B2a,R:B3b,A:S2,A:S3a,A:S8a,A:S8b,A:S7,A:S3b,A:S4,A:S5,A:S6,A:S9,A:S10,A:S11,A:S12,A:S13,R:S7,R:S2,R:S8a,R:S8b,A:Q1,A:S1")
TBLPROPERTIES("hbase.table.name" = "Car_Data_RawS");

--创建subbrdint3表
CREATE EXTERNAL TABLE subbrdint3(ROWKEY BINARY,S2 STRING,S3a STRING,S7 STRING,S8a STRING,S8b STRING,YR STRING, CX ARRAY<STRING>,IQS ARRAY<STRING>,CD ARRAY<STRING>,GJ ARRAY<STRING>,JK ARRAY<STRING>,FM STRING,RY ARRAY<STRING>,R_B1a ARRAY<STRING>,R_B2a ARRAY<STRING>,R_B3a ARRAY<STRING>,B3b ARRAY<STRING>,G1 STRING,S9 STRING,S10 STRING,Q2a STRING,Q2b STRING,Q2c STRING,B1 ARRAY<STRING>,B2 ARRAY<STRING>,B3 ARRAY<STRING>,B4 ARRAY<STRING>,B5 ARRAY<STRING>,B6 ARRAY<STRING>,B7 ARRAY<STRING>,B8 ARRAY<STRING>,A_B1a ARRAY<STRING>,A_B2a ARRAY<STRING>,A_B3a ARRAY<STRING>,B4a ARRAY<STRING>,C1 ARRAY<STRING>,C2 ARRAY<STRING>,C3 ARRAY<STRING>,C4 ARRAY<STRING>,C5 ARRAY<STRING>,A1 ARRAY<STRING>,A2 ARRAY<STRING>,A3 ARRAY<STRING>,G ARRAY<STRING>,RDINT1 ARRAY<STRING>,BRDINT2 ARRAY<STRING>,BRDINT3 ARRAY<STRING>,IQSINT3 ARRAY<STRING>,IQSINT2 ARRAY<STRING>,IQSINT1 ARRAY<STRING>,S11 STRING,S12 STRING,S13 STRING,sid BINARY,ATT ARRAY<STRING>,IMG ARRAY<STRING>,A4 ARRAY<STRING>,C6 ARRAY<STRING>,S3b STRING,attimg1 ARRAY<STRING>,attimg2 ARRAY<STRING>,attimg3 ARRAY<STRING>)
PARTITIONED BY (mth STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
COLLECTION ITEMS TERMINATED BY ','
MAP KEYS TERMINATED BY ':'
STORED AS orc

--导入数到subbrdint3
set hive.optimize.sort.dynamic.partition=true;  //分区大于10的时候使用

set mapreduce.reduce.memory.mb=5120;
set mapreduce.reduce.java.opts=-Xmx4096m;
set mapreduce.map.memory.mb=3072;
set mapreduce.map.java.opts=-Xmx2048m;

--导入数据
INSERT OVERWRITE TABLE subbrdint3
PARTITION (mth)
SELECT ROWKEY,S2,S3a,S7,S8a,S8b,YR,CX,IQS,CD,GJ,JK,FM,RY,R_B1a,R_B2a,R_B3a,B3b,G1,S9,S10,Q2a,Q2b,Q2c,B1,B2,B3,B4,B5,B6,B7,B8,A_B1a,A_B2a,A_B3a,B4a,C1,C2,C3,C4,C5,A1,A2,A3,G,RDINT1,BRDINT2,BRDINT3,IQSINT3,IQSINT2,IQSINT1,S11,S12,S13,sid,ATT,IMG,A4,C6,S3b,attimg1,attimg2,attimg3,mth FROM
brdint3_200 JOIN
(SELECT cbrdint3,ROWKEY,S2,S3a,S7,S8a,S8b,YR,CX,IQS,CD,GJ,JK,FM,RY,R_B1a,R_B2a,R_B3a,B3b,G1,S9,S10,Q2a,Q2b,Q2c,B1,B2,B3,B4,B5,B6,B7,B8,A_B1a,A_B2a,A_B3a,B4a,C1,C2,C3,C4,C5,A1,A2,A3,G,RDINT1,BRDINT2,BRDINT3,IQSINT3,IQSINT2,IQSINT1,S11,S12,S13,sid,ATT,IMG,A4,C6,S3b,attimg1,attimg2,attimg3,mth
FROM bca
LATERAL VIEW explode(brdint3) tbrdint3 AS cbrdint3) t1
ON t1.cbrdint3=brdint3_200.k;


--创建转换表(convert)
CREATE TABLE convert(k string,v string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',';
--------导入数据
LOAD DATA LOCAL INPATH "/home/hadoop/convert.txt" INTO TABLE convert;



--创建CX-BRDINT3对应表
CREATE TABLE cx_brd3(k string,v string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',';
--------导入数据
LOAD DATA LOCAL INPATH "/home/hadoop/cx_brd3.txt" INTO TABLE cx_brd3;


--创建转换表(att)
CREATE TABLE att(k String,v String)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
--------导入数据
LOAD DATA LOCAL INPATH "/home/hadoop/BRDAttri" INTO TABLE att;



--tbrdint3表（有200个车系）
CREATE TABLE brdint3_200(k string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',';
--------导入数据
LOAD DATA LOCAL INPATH "/home/hadoop/brdint3_200" INTO TABLE brdint3_200;



--汽车销量表(sales)
CREATE TABLE sales(brdint1 STRING,brdint2 STRING,brdint3 STRING,cx STRING,jan_sla STRING,feb_sla STRING,mar_sla STRING,apr_sla STRING,
may_sla STRING,jun_sla STRING,jul_sla STRING,aug_sla STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','

--导入数据
LOAD DATA LOCAL INPATH "/home/hadoop/sales" INTO TABLE sales;








